//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrekTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contents
    {
        public Contents()
        {
            this.ContentFunctions = new HashSet<ContentFunctions>();
            this.ContentImages = new HashSet<ContentImages>();
            this.ContentTags = new HashSet<ContentTags>();
        }
    
        public int ContentId { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Descriptions { get; set; }
        public string ImageFolderName { get; set; }
        public bool isFeatured { get; set; }
        public bool isActive { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<ContentFunctions> ContentFunctions { get; set; }
        public virtual ICollection<ContentImages> ContentImages { get; set; }
        public virtual ICollection<ContentTags> ContentTags { get; set; }
    }
}
