//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrekTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentFunctions
    {
        public int ContentFunctionId { get; set; }
        public int ContentId { get; set; }
        public int FunctionId { get; set; }
    
        public virtual Contents Contents { get; set; }
        public virtual Functions Functions { get; set; }
    }
}
