//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrekTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class Functions
    {
        public Functions()
        {
            this.ContentFunctions = new HashSet<ContentFunctions>();
        }
    
        public int FunctionId { get; set; }
        public string FunctionName { get; set; }
    
        public virtual ICollection<ContentFunctions> ContentFunctions { get; set; }
    }
}
