//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrekTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        public int MenuId { get; set; }
        public string MenuText { get; set; }
        public string MenuPosition { get; set; }
        public int ContentId { get; set; }
    }
}
